export const InputComponentType = {
    TEXT_INPUT: "TEXT_INPUT",
    TEXTAREA: "TEXTAREA",
    SELECT_DROPDOWN: "SELECT_DROPDOWN",
    CHECKBOX: "CHECKBOX",
    RADIO_BUTTON: "RADIO_BUTTON",
    DATE_PICKER: "DATE_PICKER",
    FILE_UPLOAD: "FILE_UPLOAD",
    ALL: "ALL"
}
